### ISSUE TITLE
connection error: unable to get local issuer certificate 

### ISSUE THREAD

**Issue by KubaMiszcz** [kevinpainchaud/simple-ftp-deploy-action#1]
cd: Fatal error: Certificate verification: unable to get local issuer certificate (9E:BD:78:A5:1B:96:30:A1:FF:D4:AE:C2:42:E5:FC:DD:A0:B8:72:9D)
mirror: Fatal error: Certificate verification: unable to get local issuer certificate (9E:BD:78:A5:1B:96:30:A1:FF:D4:AE:C2:42:E5:FC:DD:A0:B8:72:9D)

settings:
```
- name: Simple FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1
      with:
      # FTP host
        ftp_host: ftp://****:21/****.***.pl/****/
        ftp-username: ***
        ftp-password: ${{ secrets.FTP_PASSWORD }}          
        local_source_dir: dist
        dist_target_dir: "my"
#           delete: "true"
```

**Comment by kevinpainchaud** [comment]
Hi,

You are not required to specify the protocol, port, user name & password for the `ftp_host`.
You just need to fill it in with something like this:

`ftp.***. pl`

Tell me if it solves your certificate problem.

PS: You're the first person to write me an issue on Github. #emotionalMoment 😊

**Comment by Disane87** [comment]
Got the same issue with my action:
```yaml
- name: Deploy to FTP
        uses: kevinpainchaud/simple-ftp-deploy-action@v1
        with:
          # FTP host
          ftp_host: dev.la-vielie.de
          # FTP username
          ftp_username: f0129dda
          # FTP password
          ftp_password: ${{ secrets.LAVIELIE_FTP_PW }}
          # The local folder to copy
          local_source_dir: build
          # The remote folder
          dist_target_dir: .
          # Delete files not present in the local folder on the remote folder
          delete: true
```

**Comment by Disane87** [comment]
Got the same issue with my action:
```yaml
- name: Deploy to FTP
        uses: kevinpainchaud/simple-ftp-deploy-action@v1
        with:
          # FTP host
          ftp_host: [secret]
          # FTP username
          ftp_username: [secret]
          # FTP password
          ftp_password: ${{ secrets.LAVIELIE_FTP_PW }}
          # The local folder to copy
          local_source_dir: build
          # The remote folder
          dist_target_dir: .
          # Delete files not present in the local folder on the remote folder
          delete: true
```
