### ISSUE TITLE
`only_newer` ignore `local_source_dir` & `dist_target_dir` when set

### ISSUE THREAD

**Issue by DamChtlv** [kevinpainchaud/simple-ftp-deploy-action#10]
**My config looks like this:**

```
uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
with:
  ftp_host: ***
  ftp_username: ***
  ftp_password: ***
  local_source_dir: "wp-content/themes/val"
  dist_target_dir: "autodeploytest"
  only_newer: true
  exclude: "'^logs/' '^README.md' '^.git' '^.github' '^node_modules/"
```

As you can see i have a WordPress structure and want to deploy only the theme.
When i set `only_newer`, the action starts to deploy the whole repo instead:
```
Making directory `wp-admin'
Transferring file `wp-admin/about.php'
...
```
and at root level, not in the specified `dist_target_dir`

What i wanted is to deploy only newer files from my local source dir but maybe i'm missing something?

Thanks in advance
