### ISSUE TITLE
Action fails but deletes/uploads all files

### ISSUE THREAD

**Issue by alesmenzel** [kevinpainchaud/simple-ftp-deploy-action#7]
Hello, I have a strange behaviour with the action, it successfully does delete old files and uploads the new one to my ftp, but it ends with wrong status code for some reason and without any explanation or error message. Any idea what might cause this? 
Here is my setup and Github action's log:

```
    - name: FTP Deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.0
      with:
        ftp_host: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USER }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "."
        dist_target_dir: ${{ secrets.FTP_REMOTE_ROOT }}
        delete: "true"
        exclude: "'^log/' '^www/img/upload/'"
```

and this is the log
```
.. transferring files
2020-10-03T14:30:31.8344531Z Making symbolic link `vendor/bin/tester' to `../nette/tester/src/tester'
2020-10-03T14:30:31.9321196Z ln: Operation not supported: SITE SYMLINK is not supported by the server
... transferring files
2020-10-03T14:37:06.0831542Z Transferring file `www/static-nonused/typography.html'
```

<img width="481" alt="Screen Shot 2020-10-03 at 16 47 15" src="https://user-images.githubusercontent.com/8976542/94994527-673ab280-0598-11eb-82c4-c83a9308eb97.png">

**Comment by alesmenzel** [comment]
So it was indeed caused by the SITE SYMLINK error in the log, it is sad that github ignores the lftp summary and does not display it in the logs...

```
Making symbolic link `xxx/y.html' to `x.html'
ln: Access failed: 500 SITE SYMLINK is an unknown extension (x.html)
Total: 1 directory, 1 file, 1 symlink
New: 0 files, 1 symlink
Modified: 1 file, 0 symlinks
2 errors detected
55390ab1b21d:/home# echo $?
1
```

**For anyone interested, setting the `--dereference` flag of lftp fixed the issue (= copy the file instead of creating a symlink).**

```
    - name: FTP Deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.0
      with:
        ftp_host: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USER }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "."
        dist_target_dir: ${{ secrets.FTP_REMOTE_ROOT }}
        delete: "true"
        exclude: "'^log/' '^www/img/upload/'"
        other_flags: '--dereference'
```
