### ISSUE TITLE
Error on local dir

### ISSUE THREAD

**Issue by toledox82** [kevinpainchaud/simple-ftp-deploy-action#9]
I don't know why is returning this error...
```

Run kevinpainchaud/simple-ftp-deploy-action@v1.2.1
  with:
    ftp_host: ***
    ftp_username: ***
    ftp_password: ***
    local_source_dir: /public/
    dist_target_dir: /test/
    delete: false
    only_newer: false
    ignore_time: false
    disable_ssl_certificate_verification: true

.....
mirror: Access failed: /public: No such file or directory

```
